name: BanSystemNK-DA
version: 1.0.0-SNAPSHOT
api: 1.0.0
author: Mundschutziii
main: net.llamadevelopment.bansystemda.BanSystemDA
description: Discord Announcement-Addon for BanSystemNK
depend:
  - BanSystemNK